// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9zMbLNDYl_NiUUlkdf-xw9zdfjNd4Y-o',
    appId: '1:515212350438:web:6cebe6fd8e20899d19fc27',
    messagingSenderId: '515212350438',
    projectId: 'e-commerce-stuff',
    authDomain: 'e-commerce-stuff.firebaseapp.com',
    storageBucket: 'e-commerce-stuff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgw-S8obNTa4fzri0OfAFO_D_ZdbImuE',
    appId: '1:515212350438:android:c73cec170d9ae40819fc27',
    messagingSenderId: '515212350438',
    projectId: 'e-commerce-stuff',
    storageBucket: 'e-commerce-stuff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsQXlXOvRU0kQ0MApfrh2VrSszamF2D1Q',
    appId: '1:515212350438:ios:c0e6ac21720e293d19fc27',
    messagingSenderId: '515212350438',
    projectId: 'e-commerce-stuff',
    storageBucket: 'e-commerce-stuff.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsQXlXOvRU0kQ0MApfrh2VrSszamF2D1Q',
    appId: '1:515212350438:ios:c0e6ac21720e293d19fc27',
    messagingSenderId: '515212350438',
    projectId: 'e-commerce-stuff',
    storageBucket: 'e-commerce-stuff.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9zMbLNDYl_NiUUlkdf-xw9zdfjNd4Y-o',
    appId: '1:515212350438:web:cfa3f954706f67b219fc27',
    messagingSenderId: '515212350438',
    projectId: 'e-commerce-stuff',
    authDomain: 'e-commerce-stuff.firebaseapp.com',
    storageBucket: 'e-commerce-stuff.firebasestorage.app',
  );
}
